import { configApp } from '@adonisjs/eslint-config'

const databaseImports = [
  {
    name: '@adonisjs/lucid/services/db',
    message: 'Execute database queries inside a repository.',
  },
  {
    name: '@adonisjs/lucid/database',
    message: 'Inject Database inside a repository, not a controller, service, or middleware.',
  },
]

const persistenceCalls = [
  {
    selector: 'CallExpression[callee.type="MemberExpression"][callee.property.name="query"]',
    message: 'Expose an intent-named repository method instead of building a query here.',
  },
  {
    selector: 'CallExpression[callee.type="MemberExpression"][callee.property.name="related"]',
    message: 'Relationship persistence and reads belong in a repository.',
  },
  {
    selector: 'CallExpression[callee.type="MemberExpression"][callee.property.name="load"]',
    message: 'Preload relationships inside a repository.',
  },
  {
    selector: 'CallExpression[callee.type="MemberExpression"][callee.property.name="save"]',
    message: 'Persist model mutations inside a repository.',
  },
  {
    selector:
      'CallExpression[callee.type="MemberExpression"][callee.property.name=/^(attach|detach|pivotQuery|sync)$/]',
    message: 'Relationship persistence belongs in a repository.',
  },
  {
    selector:
      'CallExpression[callee.type="MemberExpression"][callee.object.type="Identifier"][callee.object.name=/^[A-Z]/][callee.property.name=/^(create|createMany|find|findBy|findOrFail|findByOrFail|first|firstOrCreate)$/]',
    message: 'Static model persistence belongs in a repository.',
  },
  {
    selector:
      'CallExpression[callee.type="MemberExpression"][callee.property.name=/^(where|orWhere|whereILike|orWhereILike|whereIn|whereNot|whereNull|whereHas|whereRaw|preload|withCount|select|orderBy|groupBy|forUpdate)$/]',
    message: 'Query-builder composition belongs in a repository.',
  },
  {
    selector: 'Property[key.name="modifyQuery"]',
    message: 'Do not leak a query-builder callback across the repository boundary.',
  },
]

export default [
  ...configApp({
    // database/schema.ts is auto-generated by Lucid ("DO NOT EDIT") and its
    // inline array formatting trips prettier — ignore the generated artifact.
    ignores: [
      'tmp/**',
      'build/**',
      'public/assets/**',
      'node_modules/**',
      '.DS_Store',
      'coverage/**',
      'database/schema.ts',
    ],
  }),
  {
    rules: {
      // Reabilitar junto do TuyauProvider e da migração para contratos de rota gerados.
      '@adonisjs/prefer-adonisjs-inertia-link': 'off',

      // `#permissions` resolves to app/modules/permissions/interfaces/permission_catalog.ts,
      // which is deliberately import-free (enums plus one helper). It is the single
      // source of the `resource.action` vocabulary for both the backend routes and
      // the frontend menu/ACL; this exception is what stops those strings from being
      // retyped inside Inertia. No other backend path belongs in this list.
      '@adonisjs/no-backend-import-in-frontend': ['error', { allowed: ['#permissions'] }],
    },
  },
  {
    files: [
      'app/modules/**/controllers/**/*.ts',
      'app/modules/**/services/**/*.ts',
      'app/shared/middleware/**/*.ts',
      'app/shared/services/**/*.ts',
    ],
    rules: {
      'no-restricted-imports': ['error', { paths: databaseImports }],
      'no-restricted-syntax': ['error', ...persistenceCalls],
    },
  },
  {
    files: ['app/modules/**/controllers/**/*.ts', 'app/shared/middleware/**/*.ts'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          paths: databaseImports,
          patterns: [
            {
              group: ['#modules/*/repositories/*', '#shared/repositories/*'],
              message: 'Controllers and middleware depend on services, not repositories.',
            },
            {
              group: ['#modules/*/models/*', '#shared/models/*'],
              message: 'Controllers and middleware consume service DTOs, not ORM models.',
              allowTypeImports: true,
            },
          ],
        },
      ],
    },
  },
]
