#!/usr/bin/env bash
#
# Builds the production .env from the local one.
#
#   ./deploy/make_env.sh [source-env] [target-env]
#
# The third-party credentials (Resend, Groq, NVIDIA, R2) are carried over
# verbatim; everything that describes *where* the app runs is overridden, and
# the infrastructure secrets (APP_KEY, database and Redis passwords) are
# generated here so the local ones never reach the server.
#
# Re-running is safe: secrets already present in the target file are kept, so a
# second run does not lock the app out of its own database.
set -euo pipefail

SOURCE_ENV="${1:-.env}"
TARGET_ENV="${2:-deploy/.env.production}"
APP_DOMAIN="${APP_DOMAIN:-benicio.juridicai.com.br}"

if [[ ! -f "$SOURCE_ENV" ]]; then
  echo "make_env: $SOURCE_ENV not found" >&2
  exit 1
fi

# Reads a key from the existing target file, so generated secrets survive reruns.
previous_value() {
  [[ -f "$TARGET_ENV" ]] || return 0
  sed -n "s/^$1=//p" "$TARGET_ENV" | head -1
}

generate_secret() {
  openssl rand -base64 32 | tr -d '\n=+/' | cut -c1-32
}

APP_KEY_VALUE="$(previous_value APP_KEY)"
DB_PASSWORD_VALUE="$(previous_value DB_PASSWORD)"
REDIS_PASSWORD_VALUE="$(previous_value REDIS_PASSWORD)"

[[ -n "$APP_KEY_VALUE" ]] || APP_KEY_VALUE="$(generate_secret)"
[[ -n "$DB_PASSWORD_VALUE" ]] || DB_PASSWORD_VALUE="$(generate_secret)"
[[ -n "$REDIS_PASSWORD_VALUE" ]] || REDIS_PASSWORD_VALUE="$(generate_secret)"

# The tunnel connector token. It is issued once by Cloudflare, so it is taken
# from a file when provided and otherwise carried over from the previous run —
# regenerating the env must never orphan the running tunnel.
TUNNEL_TOKEN_VALUE="$(previous_value TUNNEL_TOKEN)"
if [[ -n "${TUNNEL_TOKEN_FILE:-}" && -f "$TUNNEL_TOKEN_FILE" ]]; then
  TUNNEL_TOKEN_VALUE="$(tr -d '\n' <"$TUNNEL_TOKEN_FILE")"
fi

# Keys whose local value describes the developer machine, not production.
OVERRIDDEN_KEYS=(
  NODE_ENV HOST PORT APP_URL APP_KEY LOG_LEVEL
  DB_CONNECTION DB_HOST DB_PORT DB_USER DB_PASSWORD DB_DATABASE
  REDIS_HOST REDIS_PORT REDIS_PASSWORD
  BENICIO_QDRANT_URL
  APP_DOMAIN TUNNEL_TOKEN
)

TMP_ENV="$(mktemp)"
trap 'rm -f "$TMP_ENV"' EXIT

{
  echo "# Generated by deploy/make_env.sh — do not commit."
  echo "# Application credentials are inherited from the local .env; the"
  echo "# infrastructure secrets below are unique to this environment."
  echo
  echo "NODE_ENV=production"
  echo "HOST=0.0.0.0"
  echo "PORT=3333"
  echo "LOG_LEVEL=info"
  echo "APP_URL=https://${APP_DOMAIN}"
  echo "APP_DOMAIN=${APP_DOMAIN}"
  echo "APP_KEY=${APP_KEY_VALUE}"
  echo "TUNNEL_TOKEN=${TUNNEL_TOKEN_VALUE}"
  echo
  echo "DB_CONNECTION=postgres"
  echo "DB_HOST=postgres"
  echo "DB_PORT=5432"
  echo "DB_USER=benicio"
  echo "DB_PASSWORD=${DB_PASSWORD_VALUE}"
  echo "DB_DATABASE=benicio"
  echo
  echo "REDIS_HOST=redis"
  echo "REDIS_PORT=6379"
  echo "REDIS_PASSWORD=${REDIS_PASSWORD_VALUE}"
  echo
  echo "BENICIO_QDRANT_URL=http://qdrant:6333"
  echo
  echo "# --- inherited from the local .env ---"

  # Everything else comes across untouched, comments and blanks dropped.
  while IFS= read -r line; do
    [[ "$line" =~ ^[[:space:]]*# ]] && continue
    [[ -z "${line// /}" ]] && continue
    key="${line%%=*}"
    for overridden in "${OVERRIDDEN_KEYS[@]}"; do
      [[ "$key" == "$overridden" ]] && continue 2
    done
    echo "$line"
  done <"$SOURCE_ENV"
} >"$TMP_ENV"

mkdir -p "$(dirname "$TARGET_ENV")"
install -m 600 "$TMP_ENV" "$TARGET_ENV"

echo "make_env: wrote $TARGET_ENV ($(grep -c '=' "$TARGET_ENV") keys, mode 600)"
